

# url: "https://eaton-lab.org" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "/hack-the-planet" # the subpath of your site, e.g. /blog

title: "Fieldnotes-2021"

markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
